<?php
/* +***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * Contributor(s): YetiForce.com
 * *********************************************************************************** */

require_once 'modules/com_vtiger_workflow/VTWorkflowUtils.php';

/**
 * OSSMailView Field Model Class.
 */
class OSSMailView_Field_Model extends Vtiger_Field_Model
{
	private static $editableFields = ['mail_processing_status', 'note', 'assigned_user_id', 'status_assigned_time', 'status_done_time'];

	/**
	 * Function to check whether the current field is writable.
	 *
	 * @return bool
	 */
	public function isWritable()
	{
		$displayType = $this->get('displaytype');
		if (!$this->isViewEnabled() || 4 === $displayType || 5 === $displayType
			|| 0 === strcasecmp($this->getFieldDataType(), 'autogenerated')
			|| 0 === strcasecmp($this->getFieldDataType(), 'id')
			|| true === $this->isReadOnly()) {
			return false;
		}
		return true;
	}

	/**
	 * Function to check whether the current field is editable.
	 *
	 * @return bool
	 */
	public function isEditable()
	{
		return \in_array($this->getName(), self::$editableFields) ? parent::isEditable() : false;
	}

	/**
	 * Function to check whether field is ajax editable.
	 *
	 * @return bool
	 */
	public function isAjaxEditable()
	{
    return \in_array($this->getName(), self::$editableFields) ? parent::isAjaxEditable() : false;
	}
}
